name: Reusable Workflow  
on:  
  workflow_dispatch:  
    inputs:  
      param1:  
        description: 'Parameter 1'  
        required: true   
jobs:  
  my-job:  
    runs-on: ubuntu-latest  
  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  
      - name: Print Input  
        run: echo "Parameter 1: ${{ github.event.inputs.param1 }}"  
